---
- name: Install required packages..
  package:
    name:
    - sudo

- name: Se asegura que el grupo sudo existe.
  group:
    name: sudo

- name: Crea los usuarios requeridos.
  user:
    name: '{{ usuaria_name }}'
    shell: /bin/bash
    home: '/home/{{ usuaria_name }}'
    groups: sudo
    password: '*' # Para que el usuario no se cree bloqueado.
  when:
    - usuaria_name is defined
    - usuaria_name | length > 0
