---
# tasks file for usuaria
- name: Debug variables
  ansible.builtin.debug:
    msg:
      - ansible_system {{ ansible_system }}
  tags:
    - never
    - debug
 
- name: Include OS tasks
  ansible.builtin.include_tasks: "{{ ansible_system }}.yml"
